"""symbols.py — is that actually a ticker, or a word from the message?

Reads extension/optionable.txt, the ONE list of symbols this bot may trade.
That file is generated by refresh_optionable.py from tastytrade's active-equity
universe; a symbol is in it when the broker publishes an option chain for it.

WHY THIS EXISTS. The reader treats a capitalised word in front of a strike as a
ticker, which is right almost always and catastrophic occasionally:

    "...has to hold ... then can go with 773c."   ->  OPEN **WITH** 773C
    "| EXIT ALERT Ticker: NBIS Stopped out"       ->  CLOSE **EXIT**
                                                      (the real ticker is NBIS)

Blocking words one at a time does not converge — blocking VERY simply moved the
misread on to GREEN, and the month list only had abbreviations so "PROFITS FROM
JUNE" produced ticker JUNE. An allowlist ends the game: if the broker does not
list options on it, we do not send an order for it.

FAILS OPEN, LOUDLY. If the file is missing or short, every symbol is allowed
and the caller is told once. A data file that failed to load must never quietly
become a trading halt — that is a worse failure than the one it prevents.
"""

import os
import threading

HERE = os.path.dirname(os.path.abspath(__file__))
LIST = os.path.join(HERE, "extension", "optionable.txt")

_LOCK = threading.Lock()
_OK = None          # set of tradeable symbols, or None when unusable
_WHY = ""
# Below this the file is obviously truncated and is not trusted. The real one
# carries ~6,300 roots.
_MIN = 1000


def _load():
    global _OK, _WHY
    try:
        with open(LIST, encoding="utf-8") as f:
            got = set()
            for line in f:
                s = line.strip().upper()
                if s and not s.startswith("#"):
                    got.add(s)
        if len(got) < _MIN:
            _OK, _WHY = None, ("optionable.txt has only %d symbols — too short "
                               "to trust, so the ticker gate is OFF" % len(got))
        else:
            _OK, _WHY = got, "%d symbols" % len(got)
    except Exception as e:
        _OK, _WHY = None, ("optionable.txt could not be read (%s) — the ticker "
                           "gate is OFF" % str(e)[:80])
    return _OK


def ready():
    with _LOCK:
        if _OK is None and not _WHY:
            _load()
        return (_OK is not None, _WHY)


def known(sym):
    """True when we may trade it. UNKNOWN LIST == everything allowed."""
    if not sym:
        return True
    with _LOCK:
        if _OK is None and not _WHY:
            _load()
        if _OK is None:
            return True          # fail open
        return str(sym).strip().upper() in _OK


def check(sym):
    """(ok, why) — the message is written to be read by G in trades.log."""
    if not sym:
        return (True, "no symbol to check")
    s = str(sym).strip().upper()
    with _LOCK:
        if _OK is None and not _WHY:
            _load()
        if _OK is None:
            return (True, _WHY)
    if s in _OK:
        return (True, "%s is a listed optionable symbol" % s)
    return (False,
            "%s is not a tradeable symbol — the broker lists no options on it. "
            "That usually means the reader picked up a WORD from the message "
            "instead of a ticker (this is the guard that stopped OPEN WITH 773C "
            "and CLOSE EXIT). Nothing was sent." % s)


def reload_list():
    """Pick up a fresh optionable.txt without a restart."""
    global _OK, _WHY
    with _LOCK:
        _OK, _WHY = None, ""
        _load()
        return (_OK is not None, _WHY)
